'use strict';
const data=window.JOURNEY,$=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(label,url,cls='')=>/^https:\/\//.test(url||'')?`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:'';
function actions(v){let a='';if(v.coords&&/^\d+\.\d+,\d+\.\d+$/.test(v.coords))a=link('高德导航',`https://uri.amap.com/navigation?to=${v.coords},${encodeURIComponent(v.name||v.title)}&mode=car&coordinate=gaode&callnative=1`,'primary');if(v.applePlace)a+=link('苹果地图 · 地点',v.applePlace.url);a+=(v.links||[]).map(l=>link(l.label,l.url)).join('');if(v.url)a+=link('查看门票',v.url);if(v.coords)a+=`<button data-gps="${esc(v.coords)}">GPS直线距离</button>`;a+=`<button data-copy="${esc((v.name||v.title)+' '+(v.summary||''))}">复制地点</button>`;return `<div class="actions">${a}</div><div class="location-distance" aria-live="polite"></div>`}
function choice(v,i,stay=false){const title=esc(v.name);return `<details class="card choice ${v.pending?'unconfirmed':''}"><summary><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="summary-main"><strong>${title}</strong><small>${esc(v.summary)}</small><div class="price">${esc(v.price)}</div><span class="pill ${v.verified?.includes('待')||v.pending?'warning':''}">${esc(v.verified)}</span></span><span class="expand" aria-hidden="true">+</span></summary><div class="card-body">${stay?`<p>${esc(v.room)}</p><p class="evidence"><b>退改：</b>${esc(v.cancel)}</p>`:`<div class="dish-list">${v.dishes.map(d=>`<span>${esc(d)}</span>`).join('')}</div>${v.dishes.length<3?`<p class="evidence">目前仅核到 ${v.dishes.length} 道具名菜，未补写未经证实的“招牌菜”。</p>`:''}`}<p class="evidence">${esc(v.sourceSummary)}</p>${(v.comments||[]).length?`<div class="reviews"><b>小红书评论摘意</b>${v.comments.slice(0,3).map(c=>`<p>${esc(c)}</p>`).join('')}</div>`:!stay?'<p class="evidence">尚无足够同店评论样本；上方是笔记或平台资料摘要。</p>':''}${(v.cautions||[]).map(c=>`<p class="evidence caution">${esc(c)}</p>`).join('')}${actions(v)}</div></details>`}
function attraction(v){return `<article class="card">${v.photo?`<img class="cover" src="${esc(v.photo.image_url)}" alt="${esc(v.photo.label)}" loading="lazy" width="500" height="170"><div class="credit">${link(v.photo.author,v.photo.source_page)} · ${link(v.photo.license,v.photo.license_url)} · 裁切展示${v.photo.key==='aershan_autumn'?'，阿尔山秋色资料图':''}</div>`:''}<div class="card-body"><h2>${esc(v.title)}</h2><p>${esc(v.text||v.note)}</p>${v.price?`<div class="price">${esc(v.price)}</div>`:''}${v.coords||v.url?actions(v):''}</div></article>`}
function event(v,index,dayIndex){if(v.type==='drive'||v.type==='bus'||v.kind==='local_transfer')return `<div class="transfer ${v.type==='bus'?'bus':''}" id="event-${dayIndex}-${index}"><span class="transfer-line"></span><div><div class="transfer-time">${esc(v.time)}</div><strong>${esc(v.title)}</strong><p>${v.road_km!=null?`${v.road_km} 公里 · 高德基准 ${v.amap_base_min} 分 · 安排 ${v.planned_min} 分`:v.type==='bus'?'景区候车与转乘预留，非实际时刻表':'市内交通与停车预留'}${v.note?`<br>${esc(v.note)}`:''}</p></div></div>`;
 if(v.type==='plain')return `<div class="small-event" id="event-${dayIndex}-${index}"><time>${esc(v.time)}</time><div><strong>${esc(v.title)}</strong>${v.note?`<p>${esc(v.note)}</p>`:''}</div></div>`;
 return `<section class="stop ${v.type}" id="event-${dayIndex}-${index}"><div class="stop-label">${esc(v.time)}<span>${v.type==='lunch'?'午餐':v.type==='dinner'?'晚餐':v.type==='stay'?'住宿':'游玩 / 办事'}</span></div>${v.items?`<h2 class="section-title">${esc(v.title)}</h2>${v.note?`<p class="section-intro">${esc(v.note)}</p>`:''}${v.type==='stay'&&v.items.some(x=>x.pending)?`<p class="missing">已取得 ${v.items.filter(x=>!x.pending&&!x.conditional).length} 家主要房型报价；另外 ${v.items.filter(x=>x.pending).length} 家仅查询线索，另有床位或组合报价待核，尚未满足“五家达标”的要求。</p>`:''}${v.items.map((x,i)=>choice(x,i,v.type==='stay')).join('')}`:attraction(v)}</section>`}
function overview(d,i){return `<details class="schedule"><summary><span>全天时间线</span><small>${d.timeline.timeline_start}—${d.timeline.timeline_end}</small><span>＋</span></summary><div class="schedule-list">${d.stops.map((v,j)=>`<button data-jump="event-${i}-${j}"><time>${esc(v.time)}</time><span>${esc(v.title)}</span></button>`).join('')}</div></details>`}
function alternative(d){if(!d.alternate)return '';return `<details class="alternate"><summary>10/5 减负路线 <span>少约70公里</span></summary><p>呼伦湖后直接去新左旗，跳过新右旗。约 416.8 公里，纯驾驶约 6 小时 57 分，按下列余量安排预计 18:15 抵达伊尔施。</p><div class="schedule-list">${d.alternate.events.map(e=>`<div><time>${esc(e.start)}–${esc(e.end)}</time><span>${esc(e.title)}</span></div>`).join('')}</div><p>这条线的午餐改为新左旗，不去新右旗餐厅。目前有3家具体来源候选，仍缺2家。</p>${d.alternateFood.map((x,i)=>choice(x,i)).join('')}</details>`}
$('#days').innerHTML=data.days.map((d,i)=>`<button role="tab" id="tab-${i}" aria-controls="day-${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-day="${i}">${esc(d.date)}<small>DAY ${i+1}</small></button>`).join('');$('#days').setAttribute('role','tablist');
$('#pages').innerHTML=data.days.map((d,i)=>`<section class="day" id="day-${i}" role="tabpanel" aria-labelledby="tab-${i}" tabindex="0"><div class="day-heading"><div class="eyebrow">DAY ${String(i+1).padStart(2,'0')} / 2026 AUTUMN</div><h1>${esc(d.title)}</h1><p class="route">${esc(d.route)}</p><div class="day-stats"><span>道路约 <b>${d.timeline.road_km_total}</b> km</span><span>纯驾驶约 <b>${Math.floor(d.timeline.amap_base_min_total/60)}小时${d.timeline.amap_base_min_total%60}分</b></span></div><div class="day-note">${esc(d.note)}</div></div>${overview(d,i)}${alternative(d)}${d.stops.map((v,j)=>event(v,j,i)).join('')}<p class="data-date">资料核验 2026.09.23 · 价格与营业时间为快照<br>候选中仍有点评交叉核验、菜品和房价缺口</p></section>`).join('');
const pages=$('#pages');let current=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function setDay(i,focus=false){current=Math.max(0,Math.min(data.days.length-1,i));pages.scrollTo({left:pages.clientWidth*current,behavior:reduced?'instant':'smooth'});sync();if(focus)$(`#tab-${current}`).focus()}
function sync(){document.querySelectorAll('[data-day]').forEach((b,i)=>{b.setAttribute('aria-selected',i===current);b.tabIndex=i===current?0:-1});$('#page-status').textContent=`${current+1} / ${data.days.length} · 左右滑动切换日期`;$('#prev').disabled=!current;$('#next').disabled=current===data.days.length-1}
document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>setDay(+b.dataset.day));$('#days').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();setDay(e.key==='Home'?0:e.key==='End'?6:current+(e.key==='ArrowRight'?1:-1),true)}};pages.onscroll=()=>{current=Math.max(0,Math.min(6,Math.round(pages.scrollLeft/pages.clientWidth)));sync()};$('#prev').onclick=()=>setDay(current-1);$('#next').onclick=()=>setDay(current+1);window.addEventListener('resize',()=>pages.scrollTo({left:current*pages.clientWidth,behavior:'instant'}));
$('#about-button').onclick=()=>$('#about').showModal();$('#close-about').onclick=()=>$('#about').close();$('#about').addEventListener('click',e=>{if(e.target===$('#about'))$('#about').close()});
document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{const t=document.getElementById(b.dataset.jump);t.closest('.day').scrollTo({top:t.offsetTop-12,behavior:reduced?'instant':'smooth'})});
let timer;function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,3500)}
document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);toast('地点已复制')}catch{toast('当前浏览器不支持复制，请长按地点文字')}});

function delta(lon,lat){
 const x=lon-105,y=lat-35,pi=Math.PI;
 let a=-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x));
 a+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;
 a+=(20*Math.sin(y*pi)+40*Math.sin(y/3*pi))*2/3;
 a+=(160*Math.sin(y/12*pi)+320*Math.sin(y*pi/30))*2/3;
 let b=300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x));
 b+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;
 b+=(20*Math.sin(x*pi)+40*Math.sin(x/3*pi))*2/3;
 b+=(150*Math.sin(x/12*pi)+300*Math.sin(x/30*pi))*2/3;
 const rad=lat*pi/180,s=Math.sin(rad),magic=1-.006693421622965943*s*s,sqrt=Math.sqrt(magic);
 return [b*180/(6378245/sqrt*Math.cos(rad)*pi),a*180/((6378245*(1-.006693421622965943))/(magic*sqrt)*pi)];
}
function toWgs(c){if(c[0]<72.004||c[0]>137.8347||c[1]<.8293||c[1]>55.8271)return [c[1],c[0]];const d=delta(...c);return [c[1]-d[1],c[0]-d[0]];}
function haversine(a,b){const rad=Math.PI/180,dLat=(b[0]-a[0])*rad,dLon=(b[1]-a[1])*rad;const v=Math.sin(dLat/2)**2+Math.cos(a[0]*rad)*Math.cos(b[0]*rad)*Math.sin(dLon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));}
document.querySelectorAll('[data-gps]').forEach(b=>b.onclick=()=>{const out=b.closest('.card-body').querySelector('.location-distance');if(!navigator.geolocation){out.textContent='当前浏览器不支持定位';return}out.textContent='正在获取当前位置…';b.disabled=true;navigator.geolocation.getCurrentPosition(p=>{b.disabled=false;const age=Date.now()-p.timestamp;if(age>120000||p.coords.accuracy>1000){out.textContent='定位过旧或误差超过1公里，请到开阔处重试。';return}const d=haversine([p.coords.latitude,p.coords.longitude],toWgs(b.dataset.gps.split(',').map(Number)));out.textContent=`直线约 ${(d/1000).toFixed(1)} 公里 · 定位误差约 ${Math.round(p.coords.accuracy)} 米 · ${new Date(p.timestamp).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}；不是公路距离。`},e=>{b.disabled=false;out.textContent=e.code===1?'未获得定位授权，可继续离线阅读。':'暂未取得有效定位，请到开阔处重试。'},{enableHighAccuracy:true,timeout:20000,maximumAge:0})});
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(async r=>{await navigator.serviceWorker.ready;$('#offline-status').textContent='离线文字资料已保存；外部图片、订票和地图跳转需网络。';r.update();}).catch(()=>$('#offline-status').textContent='离线保存失败，请联网重新打开。');navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!window._swReloaded){window._swReloaded=true;location.reload()}})}else $('#offline-status').textContent='当前浏览器不支持离线保存。';
sync();
