'use strict';
const days=window.JOURNEY.days,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=u=>/^https:\/\//.test(u||'');const ext=(label,url,cls='')=>safe(url)?`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:'';
const coords=v=>typeof v==='string'&&/^\d+\.\d+,\d+\.\d+$/.test(v)?v.split(',').map(Number):null;
const nav=(v)=>v.coords?`https://uri.amap.com/navigation?to=${v.coords},${encodeURIComponent(v.name||v.title)}&mode=car&coordinate=gaode&callnative=1`:`https://uri.amap.com/search?keyword=${encodeURIComponent((v.name||v.title)+' '+(v.summary||''))}&callnative=1`;
const cards=[];let active=0;
const geo=window.JOURNEY.geography||{days:[]};
function makeCards(day,di){return day.stops.map((stop,si)=>{const fixed=geo.days[di]?.attractions?.find(x=>x.title===stop.title);const loc=coords(stop.coords)||coords(fixed?.coords);const legs=stop.type==='drive'?(geo.days[di]?.segments||[]).filter(x=>x.route===stop.route):[];const prior=day.stops[si-1];const c={...stop,key:cards.length,di,loc,chosen:stop,legs,locationStatus:({missing_exact_coordinates:'精确停靠点待核，不画推测路线。',scenic_parking:'导航位置为景区停车场。',scenic_ticket_office:'导航位置为景区售票处。'})[fixed?.status],arrival:stop.type==='attraction'&&prior?.kind==='local_transfer'?prior:null};c.points=(stop.items||[]).map((v,i)=>({...v,index:i+1,loc:coords(v.coords)})).filter(v=>v.loc);c.mapLine=c.legs.flatMap(l=>l.line||[]);cards.push(c);return c})}
const dayCards=days.map(makeCards);
for(const day of dayCards){for(let i=0;i<day.length;i++){const c=day[i];if(c.items){c.before=day.slice(0,i).reverse().find(x=>x.type==='attraction');c.after=day.slice(i+1).find(x=>x.type==='attraction');}}}
function shortTitle(c){if(c.items)return c.type==='stay'?'住在哪里':'沿途吃什么';return c.title.replace('（体力允许）','').replace('正规景区短停','').replace('周边合法开放点','').replace('河曲观景','河').replace('合法停车点短停','得耳布尔 · 林间短停').replace('顺丰验视、包装、收寄预留','顺丰寄回无人机')}
function excerpt(c){if(c.items)return c.items.map((v,i)=>`${i+1}. ${v.name}`).join('　');return c.text||c.note||(c.type==='attraction'?'按现场开放情况游览。':'按时间安排，现场可酌情调整。')}
function meta(c){if(c.items)return c.type==='stay'?'目标约 ¥100 / 人 / 晚 · 男女分房，有独立房门；原候选含超预算，详见筛选结果':`${c.points.length} 家已定位 / ${c.items.length} 家备选 · 点编号对应下方名单`;if(c.type==='drive')return `${c.road_km} 公里 · 高德基准 ${c.amap_base_min} 分钟 / 计划预留 ${c.planned_min} 分钟`;if(c.legs.length)return `${c.legs.reduce((n,l)=>n+(+l.road_km||0),0).toFixed(1)} 公里 · ${c.legs[0].from} → ${c.legs.at(-1).to}`;return c.price||''}
function renderCard(c){if(['plain','bus'].includes(c.type))return `<article class="card compact"><div class="body"><span class="time">${esc(c.time)}${c.type==='bus'?' · 景区接驳预留':''}</span><h2>${esc(c.title)}</h2><p>${esc(excerpt(c))}</p></div></article>`;let available=c.loc||c.mapLine.length||c.points.length;const label=c.items?`${c.points.length} 个${c.type==='stay'?'住宿':'餐厅'}位置 · 不连线`:c.legs.length?`${c.legs[0].from} → ${c.legs.at(-1).to}`:shortTitle(c)+' · 地点位置';const map=available?`<div class="map-link"><div class="mini-map" id="map-${c.key}" data-map="${c.key}"></div><div class="map-tag"><span>${esc(label)}</span></div></div>`:`<div class="map-unavailable">${c.type==='attraction'?'此处精确位置 / 园内接驳路线待核，未绘制道路':'候选精确位置待核'}</div>`;const context=c.items?`<div class="map-context">${esc(c.before?shortTitle(c.before):days[c.di].route.split('→')[0])}之后 · ${esc(c.after?shortTitle(c.after):c.type==='stay'?'当晚住宿区域':'当日停留区域')}一带${c.points.length<c.items.length?' · 未定位候选见详情':''}</div>`:'';return `<article class="card">${map}${context}<div class="body"><span class="time">${esc(c.time)}</span><h2>${esc(shortTitle(c))}</h2><p class="${c.items?'candidate-names':''}">${esc(excerpt(c))}</p><p class="sub">${esc(meta(c))}</p>${c.arrival?`<p class="sub">到达安排：${esc(c.arrival.time)} ${esc(c.arrival.title)}。${esc(c.arrival.note||'')}</p>`:''}${c.locationStatus?`<p class="sub">${esc(c.locationStatus)}</p>`:''}</div><div class="actions">${!c.items&&c.type!=='drive'?ext(c.loc?'高德导航':'高德查位置',nav({...c,coords:c.loc?.join(',')}),'main'):''}${!c.items&&c.url?ext('门票',c.url):''}<button data-open="${c.key}">${c.items?'查看 '+c.items.length+' 个备选':'详情与来源'} ↗</button></div></article>`}
$('#dates').innerHTML=days.map((d,i)=>`<button role="tab" aria-selected="${i===0}" data-day="${i}" aria-controls="day-${i}">${esc(d.date)}</button>`).join('')+`<button role="tab" aria-selected="false" data-day="7" aria-controls="day-7">总览</button>`;$('#dates').setAttribute('role','tablist');$('#pages').innerHTML=days.map((d,i)=>`<section class="day" id="day-${i}" aria-label="${esc(d.date)}的行程"><div class="day-title"><span>${esc(d.route)}<div class="route-key">当日驾车约 ${(geo.days[i]?.segments||[]).reduce((n,l)=>n+(+l.road_km||0),0).toFixed(1)} 公里</div></span><button data-schedule="${i}">时间线</button></div>${i===0?'<p class="day-summary">上午看莫尔格勒河 → 中午到额尔古纳 → 下午入住、休息及市区步行 → 晚餐后回住处</p>':''}${dayCards[i].map(renderCard).join('')}<p class="day-footer">2026.09.23 核验 · 候选未预订<br>${i===4?'原线预计19:55抵达，减负线见时间线。':'完整资料与待核项见卡片详情。'}</p></section>`).join('');
$('#pages').insertAdjacentHTML('beforeend',`<section class="day" id="day-7" aria-label="全程总览"><div class="day-title"><span>海拉尔 → 阿尔山 · 全程总览</span></div><article class="card"><div id="overview-map" class="overview-map"></div><div class="legend"><span><i class="route"></i>固定行程</span><span><i></i>餐厅备选</span><span><i class="hotel"></i>住宿备选</span></div><div class="body"><h2>一路向秋天</h2><p>线路与每日卡片共用数据。点击地点查看名称；餐厅与住宿只标位置，选好后再导航。</p><p class="sub">园内接驳和未定位地点不伪造道路。终点暂按租车截图安排在阿尔山。</p><div class="overview-days">${days.map((d,i)=>`<button data-filter="${i}">${d.date}</button>`).join('')}<button data-filter="all">全程</button></div></div></article></section>`);
function sync(){if(active===7)setTimeout(initOverview,60);document.querySelectorAll('[data-day]').forEach((b,i)=>{b.setAttribute('aria-selected',i===active);b.tabIndex=i===active?0:-1})}function setDay(i){active=Math.max(0,Math.min(days.length,i));$('#pages').scrollTo({left:active*$('#pages').clientWidth,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});sync()}
document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>setDay(+b.dataset.day));$('#pages').onscroll=()=>{active=Math.max(0,Math.min(days.length,Math.round($('#pages').scrollLeft/$('#pages').clientWidth)));sync()};$('#dates').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();setDay(active+(e.key==='ArrowRight'?1:-1));document.querySelector(`[data-day="${active}"]`).focus()}};window.addEventListener('resize',()=>$('#pages').scrollTo({left:active*$('#pages').clientWidth,behavior:'instant'}));
function show(html){$('#detail-body').innerHTML=html;$('#detail').showModal();$('#detail').scrollTop=0}$('#close').onclick=()=>$('#detail').close();$('#detail').onclick=e=>{if(e.target===$('#detail'))$('#detail').close()};
function links(v){return `${coords(v.coords)?`<button data-gps="${esc(v.coords)}">GPS直线距离</button>`:''}<button data-copy="${esc((v.name||v.title)+' '+(v.summary||''))}">复制地点</button>`+`${ext('高德',nav(v))}${v.applePlace?ext('苹果地图 · 地点',v.applePlace.url):'<span class="apple-pending">苹果地点未核实</span>'}${(v.links||[]).map(l=>ext(l.label,l.url)).join('')}${v.url?ext('门票来源',v.url):''}`}
const budgetSummary=['10/1：凯宾思 ¥449，价格达标；房门和床位待核。','10/2：久居 ¥473.10，价格达标；房门和床位待核。','10/3：暂未找到达标报价，已核最低瓦罗佳 ¥592。','10/4：以南 ¥384、塔拉格日 ¥458、君领 ¥469，价格达标；房门和床位待核。','10/5–6：暂未找到达标报价。张老师两晚均价 ¥633 且含沙发床，不算合格。','10/5–6：暂未找到达标报价。张老师两晚均价 ¥633 且含沙发床，不算合格。'];
function candidate(v,stay){return `<section class="candidate"><h3>${esc(v.name)}</h3><small>${esc(v.summary)}</small><p class="price">${esc(v.price)}</p><small>${esc(v.verified)}</small>${stay?`<p>${esc(v.room)}</p><p>退改：${esc(v.cancel)}</p>`:`<p>${esc(v.dishes.join(' · ')||'菜品待核')}</p>`}<p>${esc(v.sourceSummary)}</p>${v.comments?.length?'<small>小红书评论摘意</small>'+v.comments.map(x=>`<p>${esc(x)}</p>`).join(''):''}${(v.cautions||[]).map(x=>`<small>${esc(x)}</small>`).join('')}<div class="detail-links">${links(v)}</div></section>`}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const c=cards[+b.dataset.open];let content=`<h2>${esc(shortTitle(c))}</h2><small>${esc(c.time)}</small>`;if(c.items){content+=`<p>${esc(c.type==='stay'?'新目标：5人合计约500元/晚，男女分房，卧室须有独立房门。以下保留原始报价供比较，并非都符合新预算；房门和床位尚待逐项核实。':c.note||'在同一片区域择一用餐；价格和营业时间以到店为准。')}</p>`+(c.type==='stay'?`<p class="price">${esc(budgetSummary[c.di]||'报价待核')}</p><p>以上为五人整套每晚报价口径，非实时锁价。价格达标不代表已满足男女分房要求。</p>`:'')+c.items.map(v=>candidate(v,c.type==='stay')).join('')}else{if(c.photo)content+=`<img class="detail-photo" src="${esc(c.photo.image_url)}" alt="${esc(c.photo.label)}"><small>${ext(c.photo.author,c.photo.source_page)} · ${ext(c.photo.license,c.photo.license_url)} · 裁切展示</small>`;content+=`<p>${esc(c.text||c.note)}</p><p class="price">${esc(c.price||'')}</p><div class="detail-links">${links(c)}</div>`}if(c.mapTarget)content+=`<p>卡片小图终点为${esc(c.mapTarget.name)}，不是景区内部景点入口。</p>`;if(c.legs.length)content+=c.legs.map(l=>`<p>${esc(l.from)} → ${esc(l.to)} · ${esc(l.road_km)}公里（已存高德路段）</p>`).join('');show(content)});
const scheduleHtml=es=>es.map(e=>`<div class="schedule-row"><time>${esc(e.start)}–${esc(e.end)}</time><div>${esc(e.title)}${e.road_km!=null?`<small>${e.road_km}公里 · 基准${e.amap_base_min}分 / 预留${e.planned_min}分</small>`:''}${e.note?`<small>${esc(e.note)}</small>`:''}</div></div>`).join('');document.querySelectorAll('[data-schedule]').forEach(b=>b.onclick=()=>{const d=days[+b.dataset.schedule];show(`<h2>${esc(d.date)} · 时间线</h2><p>${esc(d.note)}</p>${scheduleHtml(d.timeline.events)}${d.alternate?`<h2>减负路线</h2><p>跳过新右旗，经新左旗到伊尔施；预计18:15抵达。</p>${scheduleHtml(d.alternate.events)}`:''}<p>车程为已有高德查询的规划值；园内接驳时间不是官方班次。${+b.dataset.schedule===6?'终点按租车截图在阿尔山编排，仍以实际交通安排为准。':''}</p>`) });
document.querySelectorAll('[data-nav]').forEach(a=>{a.onclick=e=>{if(!e.target.closest('.leaflet-control-attribution'))window.open(a.dataset.nav,'_blank','noopener')};a.onkeydown=e=>{if(e.key==='Enter')window.open(a.dataset.nav,'_blank','noopener')}});

function delta(lon,lat){
 const x=lon-105,y=lat-35,pi=Math.PI;
 let a=-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x));
 a+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;
 a+=(20*Math.sin(y*pi)+40*Math.sin(y/3*pi))*2/3;
 a+=(160*Math.sin(y/12*pi)+320*Math.sin(y*pi/30))*2/3;
 let b=300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x));
 b+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;
 b+=(20*Math.sin(x*pi)+40*Math.sin(x/3*pi))*2/3;
 b+=(150*Math.sin(x/12*pi)+300*Math.sin(x/30*pi))*2/3;
 const rad=lat*pi/180,s=Math.sin(rad),magic=1-.006693421622965943*s*s,sqrt=Math.sqrt(magic);
 return [b*180/(6378245/sqrt*Math.cos(rad)*pi),a*180/((6378245*(1-.006693421622965943))/(magic*sqrt)*pi)];
}
function toWgs(c){if(c[0]<72.004||c[0]>137.8347||c[1]<.8293||c[1]>55.8271)return [c[1],c[0]];const d=delta(...c);return [c[1]-d[1],c[0]-d[0]];}
function haversine(a,b){const rad=Math.PI/180,dLat=(b[0]-a[0])*rad,dLon=(b[1]-a[1])*rad;const v=Math.sin(dLat/2)**2+Math.cos(a[0]*rad)*Math.cos(b[0]*rad)*Math.sin(dLon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));}
const maps=[];
function baseMap(el,interactive=false){const m=L.map(el,{zoomControl:interactive,dragging:interactive,scrollWheelZoom:interactive,doubleClickZoom:interactive,touchZoom:interactive,boxZoom:false,keyboard:interactive,attributionControl:true});m.attributionControl.setPrefix(false);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>'}).addTo(m);maps.push(m);return m}
function pin(m,loc,label,kind='',number=''){return L.marker(toWgs(loc),{icon:L.divIcon({className:'point-number '+kind,html:esc(number),iconSize:[24,24],iconAnchor:[12,12]})}).addTo(m).bindPopup(esc(label))}
function fit(m,pts){if(pts.length)m.fitBounds(L.latLngBounds(pts),{paddingTopLeft:[32,49],paddingBottomRight:[32,26],maxZoom:14});else m.setView([49,120],6)}
const observe=new IntersectionObserver(es=>{for(const e of es){if(!e.isIntersecting)continue;observe.unobserve(e.target);const c=cards[+e.target.dataset.map],m=baseMap(e.target),pts=[];
if(c.items){for(const v of c.points){pts.push(toWgs(v.loc));pin(m,v.loc,`${v.index}. ${v.name}`,c.type==='stay'?'hotel':'',v.index)}
// Context markers are included only when nearby, to keep individual alternatives legible.
for(const v of [c.before,c.after])if(v?.loc&&c.points.some(p=>haversine(toWgs(p.loc),toWgs(v.loc))<18000)){pts.push(toWgs(v.loc));pin(m,v.loc,shortTitle(v),'context','景')}
}else{for(const l of c.legs){if(l.line?.length>1){const path=l.line.map(toWgs);pts.push(...path);L.polyline(path,{color:'#8175c8',weight:3.5,opacity:.9}).addTo(m);pin(m,l.line[0],l.from,'context','起');pin(m,l.line.at(-1),l.to,'context','终')}}if(c.loc){pts.push(toWgs(c.loc));pin(m,c.loc,shortTitle(c),'context','景')}}fit(m,pts)}},{root:$('#pages'),rootMargin:'80px'});document.querySelectorAll('[data-map]').forEach(el=>observe.observe(el));
let overview=null,overviewLayer=null;function initOverview(){if(!overview){overview=baseMap('overview-map',true);drawOverview('all')}overview.invalidateSize()}
function drawOverview(filter){if(!overview)return;if(overviewLayer)overview.removeLayer(overviewLayer);overviewLayer=L.layerGroup().addTo(overview);const pts=[],seen=new Set();geo.days.forEach((d,i)=>{if(filter!=='all'&&i!==+filter)return;for(const l of d.segments||[]){if(l.line?.length>1){const line=l.line.map(toWgs);pts.push(...line);L.polyline(line,{color:['#8175c8','#638eae','#63a29b','#bb9867','#b17f9b','#7e9f5d','#8c87a6'][i],weight:3}).bindPopup(`${esc(days[i].date)} · ${esc(l.from)} → ${esc(l.to)}`).addTo(overviewLayer)}}});for(const c of cards){if(filter!=='all'&&c.di!==+filter)continue;for(const v of c.items?c.points:c.loc?[{loc:c.loc,name:shortTitle(c)}]:[]){const id=(v.name||'')+v.loc.join(',');if(seen.has(id))continue;seen.add(id);const p=toWgs(v.loc);pts.push(p);L.circleMarker(p,{radius:c.items?4:6,color:'#fff',weight:1.5,fillOpacity:.95,fillColor:c.items?c.type==='stay'?'#3e918a':'#d58b40':'#8175c8'}).bindPopup(esc(v.name)).addTo(overviewLayer)}}fit(overview,pts)}document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>drawOverview(b.dataset.filter));
window.addEventListener('resize',()=>maps.forEach(m=>m.invalidateSize()));
$('#detail-body').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.copy){try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='已复制'}catch{b.textContent='请长按地点复制'}}if(b.dataset.gps){let out=b.parentNode.querySelector('.gps-result');if(!out){out=document.createElement('p');out.className='gps-result';out.setAttribute('role','status');b.parentNode.append(out)}if(!navigator.geolocation){out.textContent='当前浏览器不支持定位';return}out.textContent='正在定位…';navigator.geolocation.getCurrentPosition(p=>{if(Date.now()-p.timestamp>120000||p.coords.accuracy>1000){out.textContent='定位过旧或误差过大，请到开阔处重试。';return}const distance=haversine([p.coords.latitude,p.coords.longitude],toWgs(coords(b.dataset.gps)));out.textContent=`直线约 ${(distance/1000).toFixed(1)} 公里 · 误差约 ${Math.round(p.coords.accuracy)} 米；不是公路距离。`},()=>out.textContent='尚未取得有效定位，可继续查看攻略。',{enableHighAccuracy:true,timeout:20000,maximumAge:0})}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
function offline(){document.querySelectorAll('.map-tag span:first-child').forEach(s=>{if(!s.dataset.original)s.dataset.original=s.textContent;s.textContent=navigator.onLine?s.dataset.original:'离线 · 仅保留已存路线与地点'})}window.addEventListener('online',offline);window.addEventListener('offline',offline);offline();
