'use strict';
const days=window.JOURNEY.days,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=u=>/^https:\/\//.test(u||'');const ext=(label,url,cls='')=>safe(url)?`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:'';
const coords=v=>typeof v==='string'&&/^\d+\.\d+,\d+\.\d+$/.test(v)?v.split(',').map(Number):null;
const nav=(v)=>v.coords?`https://uri.amap.com/navigation?to=${v.coords},${encodeURIComponent(v.name||v.title)}&mode=car&coordinate=gaode&callnative=1`:`https://uri.amap.com/search?keyword=${encodeURIComponent((v.name||v.title)+' '+(v.summary||''))}&callnative=1`;
const cards=[];let active=0;
const geo=window.JOURNEY.geography||{days:[]};
function makeCards(day,di){return day.stops.map((stop,si)=>{const fixed=geo.days[di]?.attractions?.find(x=>x.title===stop.title);const loc=coords(stop.coords)||coords(fixed?.coords);const legs=stop.type==='drive'?(geo.days[di]?.segments||[]).filter(x=>x.route===stop.route):[];const prior=day.stops[si-1];const c={...stop,key:cards.length,di,loc,chosen:stop,legs,locationStatus:({missing_exact_coordinates:'具体停靠点待核。',scenic_parking:'导航位置为景区停车场。',scenic_ticket_office:'导航位置为景区售票处。'})[fixed?.status],arrival:stop.type==='attraction'&&prior?.kind==='local_transfer'?prior:null};c.points=(stop.items||[]).map((v,i)=>({...v,index:i+1,loc:coords(v.coords)})).filter(v=>v.loc);c.mapLine=c.legs.flatMap(l=>l.line||[]);cards.push(c);return c})}
const dayCards=days.map(makeCards);
for(const day of dayCards){for(let i=0;i<day.length;i++){const c=day[i];if(c.items){c.before=day.slice(0,i).reverse().find(x=>x.type==='attraction');c.after=day.slice(i+1).find(x=>x.type==='attraction');}}}
function shortTitle(c){if(c.items)return c.type==='stay'?'住在哪里':'沿途吃什么';return c.title.replace('（体力允许）','').replace('正规景区短停','').replace('周边合法开放点','').replace('河曲观景','河').replace('合法停车点短停','得耳布尔 · 林间短停').replace('顺丰验视、包装、收寄预留','顺丰寄回无人机')}
function excerpt(c){if(c.type==='stay')return `民宿 ${c.items.filter(v=>v.lodgingType==='民宿').length} 家 · 酒店 ${c.items.filter(v=>v.lodgingType==='酒店').length} 家，查看房型和价格`;if(c.items)return c.items.slice(0,3).map((v,i)=>`${i+1}. ${v.name}`).join('　')+(c.items.length>3?` 等 ${c.items.length} 家`:'');return c.text||c.note||(c.type==='attraction'?'按现场开放情况游览。':'按时间安排，现场可酌情调整。')}
function meta(c){if(c.items)return c.type==='stay'?'优先 ¥100–130 / 人 / 晚 · ¥130–150 为次选':`${c.items.length} 家备选 · 查看菜品和人均价格`;if(c.type==='drive')return `${c.road_km} 公里 · 高德基准 ${c.amap_base_min} 分钟 / 计划预留 ${c.planned_min} 分钟`;if(c.legs.length)return `${c.legs.reduce((n,l)=>n+(+l.road_km||0),0).toFixed(1)} 公里 · ${c.legs[0].from} → ${c.legs.at(-1).to}`;return c.price||''}
// Editorial review assessment 65%, platform ratings 25%, price value 10%.
function stayScore(v){
 const review=v.reviewAssessment?.score, price=v.nightTotalSnapshot;
 if(!Number.isFinite(review)||!Number.isFinite(price))return null;
 const unique=new Map();for(const r of v.platformRatings||[]){if(Number.isFinite(r.score)&&r.scale>0&&r.score>=0&&r.score<=r.scale)unique.set(r.platformFamily||r.platform,r.score/r.scale*100)}
 const platform=unique.size?[...unique.values()].reduce((a,b)=>a+b,0)/unique.size:null;
 const value=price<=500?100:price<=650?80:price<=750?50:0;
 const weight=platform===null?75:100;
 return {total:Math.round((review*65+(platform??0)*25+value*10)/weight),review,platform,value,partial:platform===null};
}
function rankedStays(c){return c.items.map((v,i)=>({v,i,score:stayScore(v)})).sort((a,b)=>(b.score?.total??-1)-(a.score?.total??-1)||(a.v.nightTotalSnapshot??Infinity)-(b.v.nightTotalSnapshot??Infinity)||a.i-b.i)}
function scoreDetail(v,score){return `<section class="review-card"><strong>综合参考 ${score?score.total+'/100':'暂不评分'}</strong><p>${esc(v.reviewAssessment?.reason||'评价样本待补充')}</p>${score?`<p>评价内容 ${score.review} × 65% · 平台评分 ${score.platform===null?'缺失':score.platform.toFixed(1)+' × 25%'} · 性价比 ${score.value} × 10%</p>${score.partial?'<small>平台评分缺失，按已有75%权重折算为暂评分。</small>':''}`:''}<small>评价内容为有限样本的人工判断，不是平台住客均分。</small>${(v.platformRatings||[]).map(r=>`<p>${esc(r.platform)} ${r.score}/${r.scale} · ${r.reviewCount??'未知'}条评价${r.url?' · '+ext('平台来源',r.url):''}${r.evidenceNote?'<small>采集快照，部分来源可能较旧。</small>':''}</p>`).join('')}</section>`}
function stayTable(c,limit=Infinity){return `<table class="stay-table"><caption class="sr-only">${esc(days[c.di].date)}住宿价格与综合参考分</caption><thead><tr><th scope="col">住宿</th><th scope="col">人均 / 晚</th><th scope="col">参考分</th></tr></thead><tbody>${rankedStays(c).slice(0,limit).map(({v,i,score})=>`<tr><td><button class="stay-name" data-stay="${c.key}" data-item="${i}">${esc(v.name)}</button><small>${esc(v.lodgingType||'住宿')}${v.nightTotalSnapshot>650?' · 稍超预算':''}</small></td><td class="stay-money">${Number.isFinite(v.nightTotalSnapshot)?`<strong>¥${(v.nightTotalSnapshot/5).toFixed(1).replace(/\.0$/,'')}</strong><small>五人 ¥${v.nightTotalSnapshot}</small>`:'<span class="muted">待核价</span>'}</td><td class="stay-rating">${score?`<strong>${score.total}</strong><small>${score.partial?'暂评':'/ 100'}</small>`:'<span class="muted">—</span>'}</td></tr>`).join('')}</tbody></table>`}
const scoreExplanation=`<h2>综合参考分怎么算</h2><p>以住客实际体验为主，供本次住宿筛选参考。有限样本的人工判断，不是客观质量排名。</p><div class="score-rules"><p><strong>评价内容 · 65%</strong><br>结合卫生、安静、供暖、服务等具体体验，兼顾负面反馈、日期及房型；资料多少、坐标和房门条件不加分。90附近表示样本较一致正面，80附近为正面为主，70附近为好坏并存，60及以下为明显风险。</p><p><strong>平台评分 · 25%</strong><br>各平台先按满分换算为百分制，再按独立平台等权平均。携程与Trip视为一份；无法确认同店的不计入。评分是采集快照。</p><p><strong>性价比 · 10%</strong><br>住宿体验已计入评价项，此项只以五人房型展示总价作参考：≤¥500为100，¥500–650为80，¥650–750为50，超过¥750为0。</p></div><p>按综合分排序，同分时低价在前。缺少平台分时按其余75%折算并标“暂评”；没有可判断的评价正文或价格未核则不评分。点店名查看判断依据。分房、独立房门及最终五人入住条件仍需确认。</p>`;
function renderCard(c){if(['plain','bus'].includes(c.type))return `<article class="card compact"><div class="body"><span class="time">${esc(c.time)}${c.type==='bus'?' · 景区接驳预留':''}</span><h2>${esc(c.title)}</h2><p>${esc(excerpt(c))}</p></div></article>`;let available=c.loc||c.mapLine.length||c.points.length;const label=c.items?`${c.type==='stay'?'附近住宿':'附近餐厅'}`:c.legs.length?`${c.legs[0].from} → ${c.legs.at(-1).to}`:shortTitle(c)+' · 地点位置';const map=available?`<div class="map-link"><div class="mini-map" id="map-${c.key}" data-map="${c.key}"></div><div class="map-tag"><span>${esc(label)}</span></div></div>`:`<div class="map-unavailable">${c.type==='attraction'?'具体停靠点或园内接驳位置待核':'候选精确位置待核'}</div>`;const context='';return `<article class="card">${map}${context}<div class="body"><span class="time">${esc(c.time)}</span><h2>${esc(shortTitle(c))}</h2><p class="${c.items?'candidate-names':''}">${esc(excerpt(c))}</p><p class="sub">${esc(meta(c))}</p>${c.type==='stay'?`<div class="stay-preview">${stayTable(c,3)}<div class="stay-table-note"><span>综合参考 · ${Math.min(3,c.items.length)}家速览</span><button data-score-info>评分说明</button></div></div>`:''}${c.arrival?`<p class="sub">到达安排：${esc(c.arrival.time)} ${esc(c.arrival.title)}。${esc(c.arrival.note||'')}</p>`:''}${c.locationStatus?`<p class="sub">${esc(c.locationStatus)}</p>`:''}</div><div class="actions">${!c.items&&c.type!=='drive'?ext(c.loc?'高德导航':'高德查位置',nav({...c,coords:c.loc?.join(',')}),'main'):''}${!c.items&&c.url?ext('门票',c.url):''}<button data-open="${c.key}">${c.items?'查看 '+c.items.length+' 个备选':'详情与来源'} ↗</button></div></article>`}
$('#dates').innerHTML=days.map((d,i)=>`<button role="tab" aria-selected="${i===0}" data-day="${i}" aria-controls="day-${i}">${esc(d.date)}</button>`).join('')+`<button role="tab" aria-selected="false" data-day="7" aria-controls="day-7">总览</button><button role="tab" aria-selected="false" data-day="8" aria-controls="day-8">酒店</button>`;$('#dates').setAttribute('role','tablist');$('#pages').innerHTML=days.map((d,i)=>`<section class="day" id="day-${i}" aria-label="${esc(d.date)}的行程"><div class="day-title"><span>${esc(d.route)}<div class="route-key">当日驾车约 ${(geo.days[i]?.segments||[]).reduce((n,l)=>n+(+l.road_km||0),0).toFixed(1)} 公里</div></span><button data-schedule="${i}">时间线</button></div>${i===0?'<p class="day-summary">上午看莫尔格勒河 → 中午到额尔古纳 → 下午入住、休息及市区步行 → 晚餐后回住处</p>':''}${dayCards[i].map(renderCard).join('')}<p class="day-footer">住宿与餐厅为候选 · 尚未预订<br>${i===4?'原线预计19:55抵达，减负线见时间线。':'完整资料与待核项见卡片详情。'}</p></section>`).join('');
$('#pages').insertAdjacentHTML('beforeend',`<section class="day" id="day-7" aria-label="全程总览"><div class="day-title"><span>海拉尔 → 阿尔山 · 全程总览</span></div><article class="card"><div id="overview-map" class="overview-map"></div><div class="legend"><span><i class="route"></i>固定行程</span><span><i></i>餐厅备选</span><span><i class="hotel"></i>住宿备选</span></div><div class="body"><h2>一路向秋天</h2><p>点击地图上的地点查看名称；选定餐厅或住宿后，可从详情打开导航。</p><p class="sub">景区内接驳方式待核。终点暂按租车安排在阿尔山。</p><div class="overview-days">${days.map((d,i)=>`<button data-filter="${i}">${d.date}</button>`).join('')}<button data-filter="all">全程</button></div></div></article></section>`);
$('#pages').insertAdjacentHTML('beforeend',`<section class="day hotel-hub" id="day-8" aria-label="酒店与民宿"><div class="day-title"><span>酒店与民宿 · 六晚住宿</span><button data-score-info>评分说明</button></div><p class="day-summary">按入住日期比较，价格按五人平摊。评价内容占65%，平台评分25%，性价比10%；点店名查看评价依据及平台来源。</p>${dayCards.flat().filter(c=>c.type==='stay').map(c=>`<article class="card hotel-date-card"><div class="body"><span class="time">${esc(days[c.di].date)} 入住 · 1晚</span><h2>${esc(c.title.replace('入住','').replace(' · 第二晚',''))}</h2>${stayTable(c)}<p class="sub">综合参考分 / 100 · 展示价未锁定</p></div></article>`).join('')}<p class="day-footer">9月30日住宿已安排，不在候选列表内。<br>价格与房型记录更新于 ${esc(window.JOURNEY.asOf)}。</p></section>`);
function sync(){if(active===7)setTimeout(initOverview,60);document.querySelectorAll('[data-day]').forEach((b,i)=>{b.setAttribute('aria-selected',i===active);b.tabIndex=i===active?0:-1});const tab=document.querySelector(`[data-day="${active}"]`);if(tab){const nav=$('#dates');if(tab.offsetLeft<nav.scrollLeft||tab.offsetLeft+tab.offsetWidth>nav.scrollLeft+nav.clientWidth)nav.scrollTo({left:tab.offsetLeft-nav.offsetLeft-nav.clientWidth/2+tab.offsetWidth/2,behavior:'instant'})}}function setDay(i){active=Math.max(0,Math.min(days.length+1,i));$('#pages').scrollTo({left:active*$('#pages').clientWidth,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});sync()}
document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>setDay(+b.dataset.day));$('#pages').onscroll=()=>{active=Math.max(0,Math.min(days.length+1,Math.round($('#pages').scrollLeft/$('#pages').clientWidth)));sync()};$('#dates').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();setDay(active+(e.key==='ArrowRight'?1:-1));document.querySelector(`[data-day="${active}"]`).focus()}};window.addEventListener('resize',()=>$('#pages').scrollTo({left:active*$('#pages').clientWidth,behavior:'instant'}));
function show(html){$('#detail-body').innerHTML=html.includes('class="candidate"')||html.includes('class="schedule-row"')?html:`<article class="detail-single">${html}</article>`;$('#detail').showModal();$('#detail').scrollTop=0}$('#close').onclick=()=>$('#detail').close();$('#detail').onclick=e=>{if(e.target===$('#detail'))$('#detail').close()};
function links(v){return `${coords(v.coords)?`<button data-gps="${esc(v.coords)}">GPS直线距离</button>`:''}<button data-copy="${esc((v.name||v.title)+' '+(v.summary||''))}">复制地点</button>`+`${ext('高德',nav(v))}${v.applePlace?ext('苹果地图 · 地点',v.applePlace.url):'<span class="apple-pending">苹果地点未核实</span>'}${(v.links||[]).map(l=>ext(l.label,l.url)).join('')}${v.url?ext('门票来源',v.url):''}`}
function reviewCards(v){return (v.platformReviews||[]).map(r=>`<section class="review-card"><div class="review-heading"><strong>${esc(r.platform||'游客评价')}</strong>${r.rating?`<span>${esc(r.rating)}</span>`:''}</div>${r.sample?`<small>${esc(r.sample)}</small>`:''}${(r.positives||[]).map(t=>`<p>${esc(t)}</p>`).join('')}${(r.limitations||[]).map(t=>`<p class="review-caution">${esc(t)}</p>`).join('')}${r.url?ext('查看原始评价',r.url):''}</section>`).join('')+(v.reviewCrossCheck?`<p class="review-status">${esc(v.reviewCrossCheck)}</p>`:'')}
function candidate(v,stay){const section=(label,body)=>body?`<div class="candidate-section"><span class="section-label">${esc(label)}</span>${body}</div>`:'';return `<article class="candidate"><div class="candidate-heading"><span class="candidate-kind">${esc(stay?v.lodgingType||'住宿':'餐厅')}</span><h3>${esc(v.name)}</h3>${v.summary?`<p class="candidate-address">${esc(v.summary)}</p>`:''}<p class="candidate-price">${esc(v.price||'价格待核')}</p></div><div class="candidate-content">${section(stay?'房型与入住':'主打菜',stay?`<p>${esc(v.room)}</p>`:`<p>${esc((v.dishes||[]).join(' · ')||'菜品待核')}</p>`)}${section('参考信息',[v.verified,v.sourceSummary].filter((x,i,a)=>x&&!/^(店铺候选；|指定日期五成人整套总价未核)/.test(x)&&!a.some((other,j)=>j<i&&other?.includes(x))).map(x=>`<p>${esc(x)}</p>`).join(''))}${v.comments?.length?section('小红书评论',v.comments.map(x=>`<p>${esc(x)}</p>`).join('')):''}${v.xhsNotes?.length?section(v.xhsLabel||'小红书笔记线索',v.xhsNotes.map(x=>`<p>${esc(x)}</p>`).join('')):''}${section('平台评价',reviewCards(v))}${section(stay?'预订须知':'到店提醒',[stay&&v.cancel?'退改：'+v.cancel:null,...(v.cautions||[])].filter(Boolean).map(x=>`<p>${esc(x)}</p>`).join(''))}</div><div class="detail-links">${links(v)}</div></article>`}

document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const c=cards[+b.dataset.open];let content=`<h2>${esc(shortTitle(c))}</h2><small>${esc(c.time)}</small>`;if(c.items){content+=`<p>${esc(c.type==='stay'?'5人合计目标 ¥500/晚，优先不超过 ¥650；¥650–750 为低优先备选。男女分房，卧室有实体门。':c.note||'在同一片区域择一用餐；价格和营业时间以到店为准。')}</p>`+(c.type==='stay'?`<p>报价来自房型页面，尚未核对5名成人同时下单的结算总价及优惠。</p>${c.di===5?`<p>${esc(c.note)}</p>`:''}`+[['预算内',v=>v.nightTotalSnapshot!=null&&v.nightTotalSnapshot<=650],['稍超预算 · 低优先',v=>v.nightTotalSnapshot>650],['待核价',v=>v.nightTotalSnapshot==null]].filter(([title,test])=>c.items.some(test)).map(([title,test])=>`<h2>${title} · ${c.items.filter(test).length} 家</h2>`+c.items.filter(test).map(v=>candidate(v,true)).join('')).join('')+(c.excludedItems?.length?'<details><summary>已排除的房源</summary>'+c.excludedItems.map(v=>`<p>${esc(v.name)}：${esc(v.excludedReason)}</p>`).join('')+'</details>':''):c.items.map(v=>candidate(v,false)).join(''))}else{if(c.photo)content+=`<img class="detail-photo" src="${esc(c.photo.image_url)}" alt="${esc(c.photo.label)}"><small>${ext(c.photo.author,c.photo.source_page)} · ${ext(c.photo.license,c.photo.license_url)} · 裁切展示</small>`;content+=`<p>${esc(c.text||c.note)}</p><p class="price">${esc(c.price||'')}</p>${reviewCards(c)}<div class="detail-links">${links(c)}</div>`}if(c.mapTarget)content+=`<p>导航到${esc(c.mapTarget.name)}；景区内入口请现场确认。</p>`;if(c.legs.length)content+=c.legs.map(l=>`<p>${esc(l.from)} → ${esc(l.to)} · ${esc(l.road_km)}公里</p>`).join('');show(content)});
document.querySelectorAll('[data-stay]').forEach(b=>b.onclick=()=>{const c=cards[+b.dataset.stay],v=c.items[+b.dataset.item],score=stayScore(v);show(`<h2>${esc(days[c.di].date)} · 住宿</h2>${scoreDetail(v,score)}<p>五人房型页面展示价；库存、优惠及最终成人入住条件仍需确认。</p>${candidate(v,true)}`)});
document.querySelectorAll('[data-score-info]').forEach(b=>b.onclick=()=>show(scoreExplanation));
const scheduleHtml=es=>es.map(e=>`<div class="schedule-row"><time>${esc(e.start)}–${esc(e.end)}</time><div>${esc(e.title)}${e.road_km!=null?`<small>${e.road_km}公里 · 基准${e.amap_base_min}分 / 预留${e.planned_min}分</small>`:''}${e.note?`<small>${esc(e.note)}</small>`:''}</div></div>`).join('');document.querySelectorAll('[data-schedule]').forEach(b=>b.onclick=()=>{const d=days[+b.dataset.schedule];show(`<h2>${esc(d.date)} · 时间线</h2><p>${esc(d.note)}</p>${scheduleHtml(d.timeline.events)}${d.alternate?`<h2>减负路线</h2><p>跳过新右旗，经新左旗到伊尔施；预计18:15抵达。</p>${scheduleHtml(d.alternate.events)}`:''}<p>车程仅供参考，出发前查看实时路况；园内接驳以现场公告为准。${+b.dataset.schedule===6?'终点按租车截图在阿尔山编排，仍以实际交通安排为准。':''}</p>`) });
document.querySelectorAll('[data-nav]').forEach(a=>{a.onclick=e=>{if(!e.target.closest('.leaflet-control-attribution'))window.open(a.dataset.nav,'_blank','noopener')};a.onkeydown=e=>{if(e.key==='Enter')window.open(a.dataset.nav,'_blank','noopener')}});

function delta(lon,lat){
 const x=lon-105,y=lat-35,pi=Math.PI;
 let a=-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x));
 a+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;
 a+=(20*Math.sin(y*pi)+40*Math.sin(y/3*pi))*2/3;
 a+=(160*Math.sin(y/12*pi)+320*Math.sin(y*pi/30))*2/3;
 let b=300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x));
 b+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;
 b+=(20*Math.sin(x*pi)+40*Math.sin(x/3*pi))*2/3;
 b+=(150*Math.sin(x/12*pi)+300*Math.sin(x/30*pi))*2/3;
 const rad=lat*pi/180,s=Math.sin(rad),magic=1-.006693421622965943*s*s,sqrt=Math.sqrt(magic);
 return [b*180/(6378245/sqrt*Math.cos(rad)*pi),a*180/((6378245*(1-.006693421622965943))/(magic*sqrt)*pi)];
}
function toWgs(c){if(c[0]<72.004||c[0]>137.8347||c[1]<.8293||c[1]>55.8271)return [c[1],c[0]];const d=delta(...c);return [c[1]-d[1],c[0]-d[0]];}
function haversine(a,b){const rad=Math.PI/180,dLat=(b[0]-a[0])*rad,dLon=(b[1]-a[1])*rad;const v=Math.sin(dLat/2)**2+Math.cos(a[0]*rad)*Math.cos(b[0]*rad)*Math.sin(dLon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));}
const maps=[];
function baseMap(el,interactive=false){const m=L.map(el,{zoomControl:interactive,dragging:interactive,scrollWheelZoom:interactive,doubleClickZoom:interactive,touchZoom:interactive,boxZoom:false,keyboard:interactive,attributionControl:true});m.attributionControl.setPrefix(false);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>'}).addTo(m);maps.push(m);return m}
function pin(m,loc,label,kind='',number=''){return L.marker(toWgs(loc),{icon:L.divIcon({className:'point-number '+kind,html:esc(number),iconSize:[24,24],iconAnchor:[12,12]})}).addTo(m).bindPopup(esc(label))}
function fit(m,pts){if(pts.length)m.fitBounds(L.latLngBounds(pts),{paddingTopLeft:[32,49],paddingBottomRight:[32,26],maxZoom:14});else m.setView([49,120],6)}
const observe=new IntersectionObserver(es=>{for(const e of es){if(!e.isIntersecting)continue;observe.unobserve(e.target);const c=cards[+e.target.dataset.map],m=baseMap(e.target),pts=[];
if(c.items){for(const v of c.points){pts.push(toWgs(v.loc));pin(m,v.loc,`${v.index}. ${v.name}`,c.type==='stay'?'hotel':'',v.index)}
// Context markers are included only when nearby, to keep individual alternatives legible.
for(const v of [c.before,c.after])if(v?.loc&&c.points.some(p=>haversine(toWgs(p.loc),toWgs(v.loc))<18000)){pts.push(toWgs(v.loc));pin(m,v.loc,shortTitle(v),'context','景')}
}else{for(const l of c.legs){if(l.line?.length>1){const path=l.line.map(toWgs);pts.push(...path);L.polyline(path,{color:'#8175c8',weight:3.5,opacity:.9}).addTo(m);pin(m,l.line[0],l.from,'context','起');pin(m,l.line.at(-1),l.to,'context','终')}}if(c.loc){pts.push(toWgs(c.loc));pin(m,c.loc,shortTitle(c),'context','景')}}fit(m,pts)}},{root:$('#pages'),rootMargin:'80px'});document.querySelectorAll('[data-map]').forEach(el=>observe.observe(el));
let overview=null,overviewLayer=null;function initOverview(){if(!overview){overview=baseMap('overview-map',true);drawOverview('all')}overview.invalidateSize()}
function drawOverview(filter){if(!overview)return;if(overviewLayer)overview.removeLayer(overviewLayer);overviewLayer=L.layerGroup().addTo(overview);const pts=[],seen=new Set();geo.days.forEach((d,i)=>{if(filter!=='all'&&i!==+filter)return;for(const l of d.segments||[]){if(l.line?.length>1){const line=l.line.map(toWgs);pts.push(...line);L.polyline(line,{color:['#8175c8','#638eae','#63a29b','#bb9867','#b17f9b','#7e9f5d','#8c87a6'][i],weight:3}).bindPopup(`${esc(days[i].date)} · ${esc(l.from)} → ${esc(l.to)}`).addTo(overviewLayer)}}});for(const c of cards){if(filter!=='all'&&c.di!==+filter)continue;for(const v of c.items?c.points:c.loc?[{loc:c.loc,name:shortTitle(c)}]:[]){const id=(v.name||'')+v.loc.join(',');if(seen.has(id))continue;seen.add(id);const p=toWgs(v.loc);pts.push(p);L.circleMarker(p,{radius:c.items?4:6,color:'#fff',weight:1.5,fillOpacity:.95,fillColor:c.items?c.type==='stay'?'#3e918a':'#d58b40':'#8175c8'}).bindPopup(esc(v.name)).addTo(overviewLayer)}}fit(overview,pts)}document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>drawOverview(b.dataset.filter));
window.addEventListener('resize',()=>maps.forEach(m=>m.invalidateSize()));
$('#detail-body').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.copy){try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='已复制'}catch{b.textContent='请长按地点复制'}}if(b.dataset.gps){let out=b.parentNode.querySelector('.gps-result');if(!out){out=document.createElement('p');out.className='gps-result';out.setAttribute('role','status');b.parentNode.append(out)}if(!navigator.geolocation){out.textContent='当前浏览器不支持定位';return}out.textContent='正在定位…';navigator.geolocation.getCurrentPosition(p=>{if(Date.now()-p.timestamp>120000||p.coords.accuracy>1000){out.textContent='定位过旧或误差过大，请到开阔处重试。';return}const distance=haversine([p.coords.latitude,p.coords.longitude],toWgs(coords(b.dataset.gps)));out.textContent=`直线约 ${(distance/1000).toFixed(1)} 公里 · 误差约 ${Math.round(p.coords.accuracy)} 米；不是公路距离。`},()=>out.textContent='尚未取得有效定位，可继续查看攻略。',{enableHighAccuracy:true,timeout:20000,maximumAge:0})}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
function offline(){document.querySelectorAll('.map-tag span:first-child').forEach(s=>{if(!s.dataset.original)s.dataset.original=s.textContent;s.textContent=navigator.onLine?s.dataset.original:'离线 · 地图可能无法加载'})}window.addEventListener('online',offline);window.addEventListener('offline',offline);offline();
